agents:
  frontend-dev:
    name: "Frontend Developer"
    model: "claude-opus-4-1-20250805"
    specialization: "React, TypeScript, UI/UX, WebSocket integration"
    context_files:
      - "src/frontend/**"
      - "package.json"
    instructions: |
      You are a senior frontend developer specializing in React and TypeScript.
      Focus on creating responsive, real-time trading interfaces.
      Prioritize performance and user experience.

  backend-dev:
    name: "Backend Developer"
    model: "claude-opus-4-1-20250805"
    specialization: "Node.js, Python, APIs, Database design"
    context_files:
      - "src/backend/**"
      - "requirements.txt"
    instructions: |
      You are a senior backend developer specializing in scalable API design.
      Focus on security, performance, and reliability for financial applications.
      Implement proper error handling and data validation.

  trading-dev:
    name: "Trading Systems Developer"
    model: "claude-opus-4-1-20250805"
    specialization: "Trading algorithms, Market analysis, Risk management"
    context_files:
      - "src/trading/**"
      - "strategies/**"
    instructions: |
      You are a quantitative developer with expertise in trading systems.
      Focus on implementing robust trading strategies, risk management, and market analysis.
      Ensure all financial calculations are precise and tested.

  ai-dev:
    name: "AI/ML Developer"
    model: "claude-opus-4-1-20250805"
    specialization: "Machine Learning, Deep Learning, Predictive modeling"
    context_files:
      - "src/ml/**"
      - "models/**"
    instructions: |
      You are an AI/ML engineer specializing in financial prediction models.
      Focus on feature engineering, model optimization, and real-time inference.
      Implement proper model evaluation and monitoring.
